#!/bin/bash
#######################################################
# SurVPS Script Installer v1.0.0
#######################################################

if [ $(id -u) != "0" ]; then
    echo "You need to be root to perform this command. Run \"sudo su\" to become root!"
    exit
fi
if [ -f /var/cpanel/cpanel.config ]; then
    clear
    echo "Your server installed WHM/Cpanel, please reinstall to use SurVPS Script."
    exit
fi

if [ -f /etc/psa/.psa.shadow ]; then
    clear
    echo "Your server installed Plesk, please reinstall to use SurVPS Script."
    exit
fi

if [ -f /etc/init.d/directadmin ]; then
    clear
    echo "Your server installed DirectAdmin, please reinstall to use SurVPS Script."
    exit
fi

if [ -f /etc/init.d/webmin ]; then
    clear
    echo "Your server installed Webmin, please reinstall to use SurVPS Script."
    exit
fi

if [[ -z "$(cat /etc/resolv.conf)" ]]; then
    echo ""
    echo "/etc/resolv.conf is empty. No nameserver resolvers detected !! "
    echo "Please configure your /etc/resolv.conf correctly or you will not"
    echo "be able to use the internet or download from your server."
    echo "aborting script... please re-run install"
    echo ""
    exit
fi

source /etc/os-release
VERSION_ID=(${VERSION_ID//./ })
OS_VERSION="$ID$VERSION_ID"

if [ "$OS_VERSION" != "centos7" ]; then
    echo "SurVPS Script is only compatible with CentOS 7"
    echo "Goodbye!"
    exit
fi

ACTION_FOLDER=/root/survps

if [ -d "$ACTION_FOLDER" ]; then
    rm -rf $ACTION_FOLDER
fi

if [ -f /etc/survps/scripts.conf ]; then
    echo "========================================================================="
    echo "Server/VPS cua ban da cai san SurVPS"
    echo "Hay su dung lenh sur de truy cap menu quan ly"
    echo "Chao tam biet!"
    echo "========================================================================="
    exit
fi

yum install wget yum -y
mkdir -p $ACTION_FOLDER
cd $ACTION_FOLDER
wget https://f97.xyz/survps/sur.zip --no-check-certificate
A | unzip sur.zip
cp -rf survps/* .

rm -rf sur* 
rm -f /root/install*

if [ "$1" = "wordpress" ]; then
    bash $OS_VERSION wordpress
else
    bash $OS_VERSION
fi
