#!/bin/bash

. /etc/hocvps/scripts.conf

if [ -f /usr/bin/rclone ]; then
echo "May chu da cai dat Rclone";
else
echo "May chu chua cai dat Rclone, tiep tuc cai dat Rclone"
printf "=========================================================================\n"
curl https://rclone.org/install.sh | sudo bash
printf "=========================================================================\n"
echo "Tham khao bai viet sau de duoc huong dan ket noi google drive: https://news.cloud365.vn/cau-hinh-rclone-ket-noi-voi-google-drive/"
printf "=========================================================================\n"
/usr/bin/rclone config
fi

NOW="$(date +"%d-%m-%Y")"

saoluucode()
{
        echo "Dang sao luu $website, vui long doi...."

        mkdir -p /home/$server_name/private_html/backup/$website/
        cd /home/$website/public_html/
        tar czf /home/$server_name/private_html/backup/$website/$website-$NOW.tar.gz .
	cd /home/$server_name/private_html/backup/$website/
	/usr/bin/rclone copy "$website"-"$NOW".tar.gz "$nameggdriver"

        echo "Sao luu website $website thanh cong..."
#        echo "Duong dan file backup: /home/$server_name/private_html/backup/$website/$website.tar.gz"
#        echo "Link download: http://$server_name:$admin_port/backup/$website/$website.tar.gz"
}

printf "=========================================================================\n"
printf "                             Sao Luu Code\n"
printf "=========================================================================\n"
echo -n "Nhap vao ten website ban muon sao luu toan bo code roi an [ENTER]: " 
read website
printf "=========================================================================\n"
if [ -d /home/$website/public_html/ ]; then
echo "Tiep tuc"
else
echo "Website ban nhap khong ton tai tren may chu, vui long kiem tra lai"
exit
fi
printf "=========================================================================\n"
printf "           Danh sach cac Google Drive duoc thiet lap de luu tru\n"
/usr/bin/rclone listremotes
printf "=========================================================================\n"
echo -n "Nhap vao ten google driver trong danh sach tren ( Nhap ten bao gom dau : ) de luu ban backup roi an [ENTER]: "
read nameggdriver
printf "=========================================================================\n"


if [ -d /home/$website/public_html/ ]; then
        if [ -z "$(ls -A /home/$website/public_html/)" ]; then
                echo "$website khong co du lieu"
                echo "Chao tam biet...!"
                exit
        else
                echo "Da phat hien thay $website tren server"

                if [ -f /home/$server_name/private_html/backup/$website/"$website"* ]; then
                read -r -p "Phat hien thay file sao luu cu, xoa no va tao sao luu moi ? [y/N] " response
                case $response in
                    [yY][eE][sS]|[yY]) 
                        rm -rf /home/$server_name/private_html/backup/$website/

                        saoluucode
                        ;;
                    *)
                        echo "Chao tam biet....!"
                        ;;
                esac
                else
                        saoluucode
                fi
        fi
else
        echo "Khong tim thay $website"
        echo "Chao tam biet...!"
        exit
fi

