#!/bin/bash

. /etc/survps/scripts.conf

if [ -f /usr/bin/rclone ]; then
echo "May chu da cai dat Rclone";
else
echo "May chu chua cai dat Rclone, tiep tuc cai dat Rclone"
printf "=========================================================================\n"
curl https://rclone.org/install.sh | sudo bash
printf "=========================================================================\n"
echo "Tham khao bai viet sau de duoc huong dan ket noi google drive: https://news.cloud365.vn/cau-hinh-rclone-ket-noi-voi-google-drive/"
printf "=========================================================================\n"
/usr/bin/rclone config
fi

NOW="$(date +"%d-%m-%Y")"

saoluudata ()
{
echo "Dang sao luu data $dataname..."
mkdir -p /home/$server_name/private_html/backup/$dataname
cd /home/$server_name/private_html/backup/$dataname
mysqldump -u root -p$mariadb_root_password $dataname | gzip -9 > $dataname-$NOW.sql.gz

/usr/bin/rclone copy $dataname-$NOW.sql.gz "$nameggdriver"

echo "Sao luu thanh cong!"
#echo "Duong dan file backup: /home/$server_name/private_html/backup/$dataname/$dataname.sql.gz"
#echo "Link download: http://$server_name:$admin_port/backup/$dataname/$dataname.sql.gz"
}

printf "=========================================================================\n"
printf "                             Sao Luu Data\n"
printf "=========================================================================\n"
printf "Sao luu data dang hoat dong co the dan toi file sao luu bi loi !!!\n\n"
echo -n "Nhap vao ten database ban muon sao luu roi an [ENTER]: " 
read dataname
printf "=========================================================================\n"
printf "           Danh sach cac Google Drive duoc thiet lap de luu tru\n"
/usr/bin/rclone listremotes
printf "=========================================================================\n"
echo -n "Nhap vao ten google driver trong danh sach tren ( Nhap ten bao gom dau : ) de luu ban backup roi an [ENTER]: "
read nameggdriver
printf "=========================================================================\n"

if [ -f /var/lib/mysql/$dataname/db.opt ]; then
echo "Da phat hien thay data $dataname tren server"
if [ -f /home/$server_name/private_html/backup/$dataname/"$dataname"* ]; then
read -r -p "Phat hien thay file sao luu cu, xoa no va tao sao luu moi ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    	rm -rf /home/$server_name/private_html/backup/$dataname
	
	saoluudata
        ;;
    *)
        echo "Chao tam biet....!"
        ;;
esac
else
	saoluudata
fi

else
echo "Khong tim thay $dataname tren server, vui long xem lai!"
echo "Chao tam biet...!"
exit
fi


