#!/bin/bash
cd /usr/bin/
rm -f sur
wget https://f97.xyz/survps/update/1.0.1/survps -O sur
chmod +x sur

# update menu
cd /etc/survps/menu
rm -f rclone
rm -f ketnoi-ggdriver
rm -f backup-source
rm -f backup-database
wget https://f97.xyz/survps/update/1.0.1/backup-source
wget https://f97.xyz/survps/update/1.0.1/backup-database
wget https://f97.xyz/survps/update/1.0.1/rclone
wget https://f97.xyz/survps/update/1.0.1/ketnoi-ggdriver

chmod +x backup-source backup-database rclone ketnoi-ggdriver

