#!/bin/bash

. /etc/hocvps/scripts.conf

prompt="Nhap vao lua chon cua ban: "

options=("Ket noi google drive" "Backup code toi Drive" "Backup database toi Drive")
printf "=========================================================================\n"
printf "                           Quan ly Backup\n"
printf "=========================================================================\n"
PS3="
$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
            1 ) /etc/hocvps/menu/ketnoi-ggdriver;;
            2 ) /etc/hocvps/menu/backup-source;;
	        3 ) /etc/hocvps/menu/backup-database;;

            $(( ${#options[@]}+1 )) ) printf "\nChao tam biet....!\n"; break;;
            *) echo "Ban nhap sai, vui long nhap theo so thu tu tren danh sach";continue;;

    esac

done


